name: Build image
on:
  push:
    branches:
    - master
jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Prepare destination directory
      run: |
        mkdir -p dist/tmp
        chmod uga+rwx dist/tmp

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build -v -ldflags="-s -w" -o dist/nanorss-go .

    - name: Create image
      run: podman build --tag nanorss-go:${{ github.ref_name }}-${{ matrix.arch }} --arch=${{ matrix.arch }} --file .github/Dockerfile dist

    - name: Save image file
      run: podman save nanorss-go:${{ github.ref_name }}-${{ matrix.arch }} > nanorss-go.tar

    - name: Upload image artifact
      uses: actions/upload-artifact@v2
      with:
        name: nanorss-go-${{ matrix.arch }}
        path: nanorss-go.tar
        retention-days: 1

  push:
    name: Combine and push images
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Download image artifacts
      id: download
      uses: actions/download-artifact@v2

    - name: Create manifest
      run: podman manifest create nanorss-go:${{ github.ref_name }}

    - name: Import images into Podman
      run: |
        for img in ${{ steps.download.outputs.download-path }}/*/nanorss-go.tar; do
          podman manifest add nanorss-go:${{ github.ref_name }} docker-archive:${img}
        done

    - name: Push image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
        podman manifest push --all nanorss-go docker://ghcr.io/zlogic/nanorss-go:${{ github.ref_name }}
