name: Build image
on:
  push:
    branches:
     - master
jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: CGO_ENABLED=0 go build -v -tags timetzdata -ldflags="-s -w" .

    - name: Create image
      run: docker build . --file .github/Dockerfile -t ghcr.io/zlogic/nanorss-go:${{ steps.extract_branch.outputs.short_ref }}

    - name: Push image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/zlogic/nanorss-go:${{ steps.extract_branch.outputs.short_ref }}
