name: Build image
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test
      run: go test -cover ./...

    - name: Build
      run: CGO_ENABLED=0 go build -v -tags timetzdata -ldflags="-s -w" .

    - name: Create image
      run: docker build . --file .github/Dockerfile -t ghcr.io/zlogic/nanorss-go:latest

    - name: Push image
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
        docker push ghcr.io/zlogic/nanorss-go:latest
      env:
        DOCKER_USERNAME: zlogic
        DOCKER_PASSWORD: ${{ secrets.CR_PAT }}
